//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEI.SPDocuments.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Default {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Default() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MEI.SPDocuments.Resources.Default", typeof(Default).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Fail.
        /// </summary>
        internal static string Action_Fail {
            get {
                return ResourceManager.GetString("Action_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Success.
        /// </summary>
        internal static string Action_Success {
            get {
                return ResourceManager.GetString("Action_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Unknown Error.
        /// </summary>
        internal static string Action_Unknown_Error {
            get {
                return ResourceManager.GetString("Action_Unknown_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not add undefined company..
        /// </summary>
        internal static string can_not_add_undefined_company {
            get {
                return ResourceManager.GetString("can_not_add_undefined_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not add undefined documentType.
        /// </summary>
        internal static string can_not_add_undefined_documentType {
            get {
                return ResourceManager.GetString("can_not_add_undefined_documentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not add undefined enumName..
        /// </summary>
        internal static string can_not_add_undefined_enumName {
            get {
                return ResourceManager.GetString("can_not_add_undefined_enumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not add undefined internalName..
        /// </summary>
        internal static string can_not_add_undefined_internalName {
            get {
                return ResourceManager.GetString("can_not_add_undefined_internalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to company already exists in collection. {0}.
        /// </summary>
        internal static string company_already_exists_in_collection__0 {
            get {
                return ResourceManager.GetString("company_already_exists_in_collection__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not append value from enumerated type &apos;{0}&apos;..
        /// </summary>
        internal static string Could_not_append_value_from_enumerated_type___0 {
            get {
                return ResourceManager.GetString("Could_not_append_value_from_enumerated_type___0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove value from enumerated type &apos;{0}&apos;..
        /// </summary>
        internal static string Could_not_remove_value_from_enumerated_type___0 {
            get {
                return ResourceManager.GetString("Could_not_remove_value_from_enumerated_type___0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve document at Url {0}. DocumentAcronym|{1};UserName|{2}.
        /// </summary>
        internal static string Could_not_retrieve_document_at_Url__0 {
            get {
                return ResourceManager.GetString("Could_not_retrieve_document_at_Url__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to displayNameLong already exists in collection..
        /// </summary>
        internal static string displayNameLong_already_exists_in_collection {
            get {
                return ResourceManager.GetString("displayNameLong_already_exists_in_collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to displayNameShort already exists in collection..
        /// </summary>
        internal static string displayNameShort_already_exists_in_collection {
            get {
                return ResourceManager.GetString("displayNameShort_already_exists_in_collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to documentType already exists in collection. {0}.
        /// </summary>
        internal static string documentType_already_exists_in_collection__0 {
            get {
                return ResourceManager.GetString("documentType_already_exists_in_collection__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not have ViewOriginal or ViewWatermarked privilege on document acronym {1}.
        /// </summary>
        internal static string does_not_have_ViewOriginal_or_ViewWatermarked_privilege_on_document_acronym__1_ {
            get {
                return ResourceManager.GetString("does_not_have_ViewOriginal_or_ViewWatermarked_privilege_on_document_acronym__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enumMember already exists in collection..
        /// </summary>
        internal static string enumMember_already_exists_in_collection {
            get {
                return ResourceManager.GetString("enumMember_already_exists_in_collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enumMember does not exist in collection..
        /// </summary>
        internal static string enumMember_does_not_exist_in_collection {
            get {
                return ResourceManager.GetString("enumMember_does_not_exist_in_collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enumName already exists in collection. {0}.
        /// </summary>
        internal static string enumName_already_exists_in_collection__0 {
            get {
                return ResourceManager.GetString("enumName_already_exists_in_collection__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was not saved correctly.
        /// </summary>
        internal static string File_was_not_saved_correctly {
            get {
                return ResourceManager.GetString("File_was_not_saved_correctly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was saved correctly.
        /// </summary>
        internal static string File_was_saved_correctly {
            get {
                return ResourceManager.GetString("File_was_saved_correctly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename was invalid.
        /// </summary>
        internal static string Filename_was_invalid {
            get {
                return ResourceManager.GetString("Filename_was_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;internalName already exists in collection. {0}.
        /// </summary>
        internal static string internalName_already_exists_in_collection__0 {
            get {
                return ResourceManager.GetString("internalName_already_exists_in_collection__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} filename. {1} The file must have one of these extensions {2}..
        /// </summary>
        internal static string Invalid__0__filename___1__The_file_must_have_one_of_these_extensions__2__ {
            get {
                return ResourceManager.GetString("Invalid__0__filename___1__The_file_must_have_one_of_these_extensions__2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} filename. {1} The filename must begin with {2}..
        /// </summary>
        internal static string Invalid__0__filename___1__The_filename_must_begin_with__2__ {
            get {
                return ResourceManager.GetString("Invalid__0__filename___1__The_filename_must_begin_with__2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} filename. {1} The filename must contain {2} parts..
        /// </summary>
        internal static string Invalid__0__filename___1__The_filename_must_contain__2__parts_ {
            get {
                return ResourceManager.GetString("Invalid__0__filename___1__The_filename_must_contain__2__parts_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid acronym. value:{0}.
        /// </summary>
        internal static string Invalid_acronym_value__0 {
            get {
                return ResourceManager.GetString("Invalid_acronym_value__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid delimitedSearchValues. Expected count was {0}. value: {1}.
        /// </summary>
        internal static string Invalid_delimitedSearchvalues__Expected_count_was__0_value_1 {
            get {
                return ResourceManager.GetString("Invalid_delimitedSearchvalues__Expected_count_was__0_value_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid documentType. value:{0}.
        /// </summary>
        internal static string Invalid_documentType_value__0 {
            get {
                return ResourceManager.GetString("Invalid_documentType_value__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name. value:{0}.
        /// </summary>
        internal static string Invalid_name_value__0 {
            get {
                return ResourceManager.GetString("Invalid_name_value__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No message returned..
        /// </summary>
        internal static string No_message_returned {
            get {
                return ResourceManager.GetString("No_message_returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to node does not contain a url attribute..
        /// </summary>
        internal static string node_does_not_contain_a_url_attribute {
            get {
                return ResourceManager.GetString("node_does_not_contain_a_url_attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to node does not contain a version attribute..
        /// </summary>
        internal static string node_does_not_contain_a_version_attribute {
            get {
                return ResourceManager.GetString("node_does_not_contain_a_version_attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to node does not contain any results..
        /// </summary>
        internal static string node_does_not_contain_any_results {
            get {
                return ResourceManager.GetString("node_does_not_contain_any_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid fileName - {0}; the {1} must be of type {2}.
        /// </summary>
        internal static string ParseFileName_Invalid__fileName__must_be_of_type {
            get {
                return ResourceManager.GetString("ParseFileName_Invalid__fileName__must_be_of_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission denied. {0}.
        /// </summary>
        internal static string Permission_denied {
            get {
                return ResourceManager.GetString("Permission_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |New fileName:{0}.
        /// </summary>
        internal static string RenameDocument__New_fileName__0_ {
            get {
                return ResourceManager.GetString("RenameDocument__New_fileName__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T must be an enumerated type..
        /// </summary>
        internal static string T_must_be_an_enumerated_type {
            get {
                return ResourceManager.GetString("T_must_be_an_enumerated_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The documentAcronym specified was not found. {0}.
        /// </summary>
        internal static string The_documentAcronym_specified_was_not_found___0 {
            get {
                return ResourceManager.GetString("The_documentAcronym_specified_was_not_found___0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The documentType specified was not found. {0}.
        /// </summary>
        internal static string The_documentType_specified_was_not_found___0 {
            get {
                return ResourceManager.GetString("The_documentType_specified_was_not_found___0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the enumName specified was not found. {0}.
        /// </summary>
        internal static string the_enumName_specified_was_not_found__0 {
            get {
                return ResourceManager.GetString("the_enumName_specified_was_not_found__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The internalName specified was not found. {0}.
        /// </summary>
        internal static string The_internalName_specified_was_not_found___0 {
            get {
                return ResourceManager.GetString("The_internalName_specified_was_not_found___0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The properties of this result do not contain this property name. {0}.
        /// </summary>
        internal static string The_properties_of_this_result_do_not_contain_this_property_name___0_ {
            get {
                return ResourceManager.GetString("The_properties_of_this_result_do_not_contain_this_property_name___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get web path of document..
        /// </summary>
        internal static string Unable_to_get_web_path_of_document {
            get {
                return ResourceManager.GetString("Unable_to_get_web_path_of_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error - WebService did not return values.
        /// </summary>
        internal static string Unknown_Error__WebService_did_not_return_values {
            get {
                return ResourceManager.GetString("Unknown_Error__WebService_did_not_return_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Menu Upload Is Only Valid for MEIUniversal.
        /// </summary>
        internal static string Upload_Vendor_Menu_Upload_Is_Only_Valid_for_MEIUniversal {
            get {
                return ResourceManager.GetString("Upload_Vendor_Menu_Upload_Is_Only_Valid_for_MEIUniversal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found in database. {1}|{2}|{3}.
        /// </summary>
        internal static string ValidateFields_Invalid__filename__not_found_in_database {
            get {
                return ResourceManager.GetString("ValidateFields_Invalid__filename__not_found_in_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Failed. {0}.
        /// </summary>
        internal static string Validation_Failed_0 {
            get {
                return ResourceManager.GetString("Validation_Failed_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.Count must be in range [{0}-{1}].
        /// </summary>
        internal static string Value_Count_must_be_in_range___0___1 {
            get {
                return ResourceManager.GetString("Value_Count_must_be_in_range___0___1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should be in range [{0}-{1}].
        /// </summary>
        internal static string Value_should_be_in_range___0___1 {
            get {
                return ResourceManager.GetString("Value_should_be_in_range___0___1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should be of length [{0}-{1}].
        /// </summary>
        internal static string Value_should_be_of_length___0___1 {
            get {
                return ResourceManager.GetString("Value_should_be_of_length___0___1", resourceCulture);
            }
        }
    }
}
