//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEI.Security.Cryptography {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MEI.Security.Cryptography.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EncryptedMessage is not large enough..
        /// </summary>
        internal static string EncryptedMessage_is_not_large_enough {
            get {
                return ResourceManager.GetString("EncryptedMessage_is_not_large_enough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kind is not valid. {0}.
        /// </summary>
        internal static string hmac_kind_is_not_valid {
            get {
                return ResourceManager.GetString("hmac_kind_is_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kind is not valid. {0}.
        /// </summary>
        internal static string hmac_kind_is_not_valid___0_ {
            get {
                return ResourceManager.GetString("hmac_kind_is_not_valid___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IV length must be greater than zero..
        /// </summary>
        internal static string IV_length_must_be_greater_than_zero {
            get {
                return ResourceManager.GetString("IV_length_must_be_greater_than_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key needs to be {0} bit!.
        /// </summary>
        internal static string Key_needs_to_be__0__bit {
            get {
                return ResourceManager.GetString("Key_needs_to_be__0__bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A key with the specified version number does not exist. {0}.
        /// </summary>
        internal static string key_with_the_specified_version_number_does_not_exist {
            get {
                return ResourceManager.GetString("key_with_the_specified_version_number_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyManager has zero auth keys..
        /// </summary>
        internal static string KeyManager_has_zero_auth_keys {
            get {
                return ResourceManager.GetString("KeyManager_has_zero_auth_keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyManager has zero crypt keys.
        /// </summary>
        internal static string KeyManager_has_zero_crypt_keys {
            get {
                return ResourceManager.GetString("KeyManager_has_zero_crypt_keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have a password of at least {0} characters!.
        /// </summary>
        internal static string Must_have_a_password_of_at_least__0__characters {
            get {
                return ResourceManager.GetString("Must_have_a_password_of_at_least__0__characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonSecretPayload length must be greater than zero..
        /// </summary>
        internal static string NonSecretPayload_length_must_be_greater_than_zero {
            get {
                return ResourceManager.GetString("NonSecretPayload_length_must_be_greater_than_zero", resourceCulture);
            }
        }
    }
}
